### ISSUE TITLE
To-do lists

### ISSUE THREAD

**Issue by BomScoob12** [BomScoob12/Webproject-v2#1]
# Web todo lists
### Deadline 27 November 2022
- [x] Design web
- [x] Index First paragraph [Edit]
- [x] Index (menu, link, content, picture, etc)
- [x] content and pictures Activity
- [x] content and picture diary
- [x] content About me
- [x] footer
- [x] theme and text font *important*
- [x] Diary pages 5-10
- [x] wrong words
- [x] effect others

**Comment by BomScoob12** [comment]
I have to finish in 18/11/2022
- theme and font
- content Diary (Design)
- footer
- index page

**Comment by BomScoob12** [comment]
- [x] Diary content
- [x] activity content
- [x] index content
- [x] aboutme content
Before 22 November 2022
